spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:      - id: details-service
        uri: lb://details-service
        predicates:
        - Path=/details/**
        filters:
        - RewritePath=/details/(?<path>.*), /$\{path}
