spring:
  application:
    name: magasin-gateway
  cloud:
    gateway: 
      default-filters:
      - AddResponseHeader=check-app, passe par gateway
      - AddResponseHeader=gateway, ${spring.application.name}
      routes: 
      - id: magasin_service
        uri: http://localhost:9090
        predicates: 
        - Path=/magasin/**
        filters:
        - StripPrefix=1
      - id: magasin_commande
        uri: http://localhost:9091
        predicates: 
        - Path=/commande/**
        filters:
        - StripPrefix=1